### PR TITLE
parallel suites

### PR DESCRIPTION
**Pull request by matthewnessworthy**
cherry-pick and squash of https://github.com/ThomasDelteil/paratest/tree/parallel-suites

As detailed in https://github.com/paratestphp/paratest/issues/179

Specifically, the commits in question are: 
* https://github.com/ThomasDelteil/paratest/commit/34c2eb1f91bc34102cca742a53db03db433aeb9b
* https://github.com/ThomasDelteil/paratest/commit/b03841a6bee8543485d10fa832233ea4751ed640

### CODE REVIEW

**Comment by andreasschroth** [comment]
Thank you for your PR. Is the original code author okay with getting his code merged though? Not sure regarding the legal requirements here. He never submitted a PR to us and he owns the rights on the code changes, although he made his changes public here on Github, still not sure.

**Comment by matthewnessworthy** [comment]
The MIT licence is maintained in the forked repository, and the repository is publicly available, so I don't see any issues. 
@ThomasDelteil would you mind explicitly stating whether your modifications can be used?

**Comment by ThomasDelteil** [comment]
No problem, please use them if they are useful to you.

**Comment by matthewnessworthy** [comment]
Thanks @ThomasDelteil, much appreciated!

**Comment by matthewnessworthy** [comment]
@andreasschroth I've got a single failing test with PHP 7.2 and `PHPUNIT_DEV=true`, see https://travis-ci.org/paratestphp/paratest/jobs/457505088

I'm not sure how to go about fixing it, any ideas?

**Comment by andreasschroth** [comment]
@ThomasDelteil Thank you for your response and the agreement, much appreciated. 👍 

@matthewnessworthy Well, as you already wrote in your other PR, phpunit changed some method signatures in the last dev version. I'm still going to merge this PR though, as the failing CI is not related to this PR at all. Would be awesome, if you could also update the `README.md` though.

**Comment by Slamdunk** [comment]
Test added in #494

**Pull request merged**
