### PR TITLE
Add support to write coverage text to file

### PR DESCRIPTION
**Pull request by Nyholm**
Just like for PHPUnit, you may want to store the "coverage text" to a file.

### CODE REVIEW

**Comment by Slamdunk** [comment]
Type `make` to run the build locally, if you have php installed, so you don't have to wait GA

**Comment by Nyholm** [comment]
There, finally.  =)

I should have checked for Makefiles before I flooded the CI. Anyhow, I believe this PR is ready for review

**Comment by Nyholm** [comment]
Wohoo. Thank you for merging

**Comment by Slamdunk** [comment]
Thank you for your contribution

**Pull request merged**
