### PR TITLE
[PHP 8] Warning: Private methods cannot be final as they are never overridden by other classes

### PR DESCRIPTION
**Pull request by tugmaks**
https://wiki.php.net/rfc/inheritance_private_methods
https://github.com/php/php-src/blob/php-8.0.0RC3/UPGRADING#L200

### CODE REVIEW

**Comment by Slamdunk** [comment]
Thank you very much for your welcomed PR.

I'd like to have a failing test before applying a fix, nevertheless.

I've just enabled a [build once a month](https://github.com/paratestphp/paratest/commit/c4bcc131cf695004bd6ccfccd8c6c2ed2b187a61): I'll merge this as soon as it fails :+1:

**Review by Slamdunk — APPROVED** [review]

**Comment by T2L** [comment]
This PR closes #562

@Slamdunk, what kind of a failing test you are looking for? 

There are warnings on CI: 
https://github.com/paratestphp/paratest/runs/1424857378?check_suite_focus=true#step:11:6

Somehow PHPUnit does not fail despite being told too 🤔

**Comment by T2L** [comment]
@Slamdunk thx for committing this. Any timeline for the new release?

P.S. By the way, I have found an interesting thing. This PR is green (tested with PHPUnit 9.4.0) and the master is red (9.4.3).

**Comment by Slamdunk** [comment]
> @Slamdunk thx for committing this. Any timeline for the new release?

I'd like to wait PHP 8 GA



> P.S. By the way, I have found an interesting thing. This PR is green (tested with PHPUnit 9.4.0) and the master is red (9.4.3).

I know, see https://github.com/shivammathur/setup-php/issues/342

**Comment by bytestream** [comment]
> I'd like to wait PHP 8 GA

GA today! 🎉 https://www.php.net/releases/8.0/en.php

**Comment by Slamdunk** [comment]
Released on [v6.0.0](https://github.com/paratestphp/paratest/releases/tag/v6.0.0)

**Pull request merged**
