### PR TITLE
[DO-NOT-MERGE] Test Code Coverage report

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by andreasschroth** [comment]
Can we close this?

**Comment by Slamdunk** [comment]
No, I still can't see the proper GUI. I need to ask help to someone like @localheinz but I'm busy right now

**Comment by andreasschroth** [comment]
What proper GUI exactly are you talking about?

I'm not sure I understand what you mean... https://codecov.io/gh/paratestphp/paratest/pull/465/tree/src is accessible in public, because the repo is public. So the code coverage report is public as well.

**Comment by Slamdunk** [comment]
Take a look at PHPUnit commits in master:

immagine

Two checks are CodeCov bot ones, not associated to Github Actions and with CodeCov icon. Those tells the exact commit coverage and overall coverage progression.

I can't find those ones within the ckecks available on Paratest master commits

**Comment by andreasschroth** [comment]
Hmm thanks. I tried to fix it, but nothing worked. I removed Codecov completely and reinstalled it, now I don't see any code reports anymore. The token changed, but I saved it as a secret in Github (there was none before?).

Maybe you can have a look again. At least the message in the Codecov settings that it's not installed correctly is gone.

**Comment by Slamdunk** [comment]
I found bots and GA to have some delay from configuration&setup to PR GUI.

Let's wait an hour and retry

**Comment by andreasschroth** [comment]
Ah the Codecov checks are now there in your latest PR! So seems to work now?

**Comment by Slamdunk** [comment]
Yup, hurray :clap: :tada:

**Pull request closed without merging**
