### PR TITLE
Fix propsal for issue #293: Display colors on code coverage

### PR DESCRIPTION
**Pull request by nicumicle**
Hello,

Please review the fix for displaying colors on the code coverage regarding issue #293 

This PR will display colored output, when `--colors` option is present.

Before this change, the output for  `--coverage-text --colors` had no colors.

### CODE REVIEW

**Comment by nicumicle** [comment]
Before my changes: 
image

After my changes:
image

**Comment by Slamdunk** [comment]
Hi, thank you for your contribution. Could you please add tests to prove your change does the right thing?

**Comment by nicumicle** [comment]
Hello @Slamdunk,

I just wanted to let you know that I've written tests for the changes I've made.

image

Now, the tests covers also the part for the Coverage report ( with and without colors) and also the part for the covered files ( with and without colors).

Please let me know what do you think.

**Comment by Slamdunk** [comment]
Thank you @nicumicle

**Pull request merged**
