### PR TITLE
test to proof issue 431

### PR DESCRIPTION
**Pull request by timglabisch**
see https://github.com/paratestphp/paratest/issues/431

### CODE REVIEW

**Comment by Slamdunk** [comment]
Beside coding standards, the test are passing :\

**Comment by timglabisch** [comment]
@Slamdunk could you please try to run it with `../../../../bin/paratest -c . --runner=SqliteRunner`? 
the problem just exists with the `SqliteRunner` -> is this covered by the tests?

**Comment by Slamdunk** [comment]
Oh, you need to add the corresponding test to `test/Unit/Runners/PHPUnit/RunnerTestCase.php`

**Comment by Slamdunk** [comment]
Locally, WrapperRunner seems ok, only SqliteRunner is failing

**Comment by Slamdunk** [comment]
So, I can fix this by wrapping the test execution of sqlite-wrapper with ob_start/ob_get_clean just like the wrapper, but everything messes up again when tricking the pipes this way:

```php
        for ($i = 0; $i < 5000; ++$i) {
            fputs(\STDOUT, "Iteration: %5s\n", $i);
        }
```

**Comment by timglabisch** [comment]
@Slamdunk i would prefer to read and output the pipes (and may allow to access the output). it's much easier to debug such tests when you get access to the process output. i think relying on `ob_*` is not a good idea, because in some integration tests may php's output buffer will messed up.

**Comment by Slamdunk** [comment]
Symfony\Process indeed always reads the pipes:

https://github.com/symfony/process/blob/f4619b7c317b62637c57ff7cf970139a64c0bf90/Process.php#L412-L416

And of course the Runner is working because it's using `Symfony\Process`

For the records, the only reason we're using base `proc_open` in WrapperRunner/SqliteRunner is because of:

https://github.com/paratestphp/paratest/blob/b2a16958fcb9adaad29af530d532c1e7eb436a7e/src/Runners/PHPUnit/WrapperRunner.php#L115

> i think relying on `ob_*` is not a good idea, because in some integration tests may php's output buffer will messed up.

I agree

**Pull request closed without merging**
