### PR TITLE
update of components to symfony 5

### PR DESCRIPTION
**Pull request by flug**
This update will be effective when this pull request is validated : 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4608

### CODE REVIEW

**Comment by andreasschroth** [comment]
Thanks, but why is there a flag in CI and a separate build in the matrix for Symphony 5? Either the project updates the dependencies to the latest ones or not.

**Comment by flug** [comment]
it updates the project afterwards since there are several versions of the components linked to symfony, it allows to have by specifying the version of symfony to have the components to the version of symfony fixed

**Comment by andreasschroth** [comment]
Thank you for your work, but I think that the PR also needs to include the fixes / migrations for the Symfony 5 components as well then.

**Comment by flug** [comment]
yes maybe, I'm looking at the possible changes on the library, but as long as the other pr is not merge changes are probably to be expected.

**Comment by flug** [comment]
After what I see the base code seems to be relatively updated :blush:

**Comment by garak** [comment]
php-cs-fixer released a Symfony 5 compatible version.
Can you trigger a new Travis build?

**Comment by grachevko** [comment]
any news?

**Comment by flug** [comment]
I don't know @andreasschroth

**Comment by andreasschroth** [comment]
Well, is this PR ready for review or not? The last comment by @flug didn't state anything like that.

**Comment by flug** [comment]
@andreasschroth yes ! it's ok :)

**Comment by andreasschroth** [comment]
Thanks, merged.

**Comment by flug** [comment]
thx @andreasschroth

**Comment by chq81** [comment]
@andreasschroth Hey, thanks a lot for your work. Would you mind tagging a new release?

**Comment by andreasschroth** [comment]
@chq81 New version tagged. :)

**Comment by chq81** [comment]
@andreasschroth Thanks a lot!

**Pull request merged**
