### PR TITLE
Make compatible with phpunit 7

### PR DESCRIPTION
**Pull request by luispabon**
Breaks BC with phpunit 6 (paratest needs new major version)

### CODE REVIEW

**Comment by luispabon** [comment]
@andreasschroth no travis set up yet?

**Comment by luispabon** [comment]
There's one test failing with phpunit 7:

1) ParaTest\Coverage\CoverageMergerTest::testSimpleMerge
Undefined offset: 39

/home/luis/Projects/contrib/paratest/test/unit/Coverage/CoverageMergerTest.php:65

I believe it might be due to this commit: https://github.com/sebastianbergmann/php-code-coverage/commit/1a10dfedc786eebfbdfcf0ceb6a3eefb75703c2e#diff-b2fbc27b0e544bbffcdfba89b3fb1dd4

I'm a bit stumped on how to move that one forward as I have zero idea of all these internals - is the test correct? Was a bug introduced on the coverage merger library? Should it be 39 on the previous version but 38 on the new one?

**Comment by andreasschroth** [comment]
We will fix TravisCI, it seems like it's not working anymore, because the repository got moved to a new organization.

**Comment by redaxmedia** [comment]
Nope, it is the same - I also had the issue with code coverage and skipped the test for the moment.

**Comment by julianseeger** [comment]
Well ... travis integration is back online (I guess) but I can't trigger a build for PRs. Could you please push anything into this PR to trigger travis?
I know it's not perfect but I would prefer a working build over avoiding useless commit in the log ;)

**Comment by luispabon** [comment]
Well, the difference with my PR here is that this one makes paratest compatible with both phpunit 7 and 6, up to you guys to decide @redaxmedia @julianseeger

**Comment by lsl** [comment]
@luispabon can you try to trigger travis build by closing and re-opening the PR? - if that doesn't work you'll need to push any kind of change to trigger the build again - the travis setup was broken at the time of your PR submission.

**Comment by luispabon** [comment]
👍

**Comment by lsl** [comment]
Same issue @redaxmedia ran into in  #299. 

See this comment:

https://github.com/paratestphp/paratest/blob/master/test/unit/Coverage/CoverageMergerTest.php#L27

        // Every time the two above files are changed, the line numbers
        // may change, and so these two numbers may need adjustments
        $firstFileFirstLine = 38;
        $secondFileFirstLine = 38;

Probably just need to update them to 39. Although those files haven't changed since Jul. So might be something else going on there.

**Comment by luispabon** [comment]
The problem here is that the behaviour of CodeCoverage has changed between php-code-coverage 5 and 6, and as such the line numbers are slightly different. Was CodeCoverage in 5 wrong, or is it a new bug in 6? Or just new behaviour? We need to trust I guess the current code to be correct. 

Seeing as this PR breaks compat with phpunit 6 anyway I could simply add php-code-coverage ^6 as an explicit dependency, which I reckon it should be, and change the expectation of the test. I'm adding an extra commit with these changes now.

**Comment by redaxmedia** [comment]
I closed my PR as I delete my fork already... good luck on getting this done

**Comment by Mechazawa** [comment]
What issues are preventing this PR from being accepted?

**Comment by luispabon** [comment]
I reckon this is ready to merge now, and 2.0 can be tagged next.

**Comment by xakzona** [comment]
Laravel 5.6 now required phpunit 7, please merge request

**Comment by luispabon** [comment]
@michaelgv also need to make a release so that it's available from composer. Since this is a BC change, it has to be 2.0.0

**Comment by michaelgv** [comment]
@luispabon yep, about to do

**Comment by luispabon** [comment]
Superb, thanks :+1:

**Comment by KarimGeiger** [comment]
Hi @michaelgv, thanks a lot for your hard work on this project. Really appreciated!

I'm still getting the error "brianium/paratest 1.1.0 requires phpunit/phpunit ^6.0.13" so I assume the release to 2.0 hasn't been published yet. Just wanted to ask for an ETA on when you think the release is ready.

Thanks again!

**Pull request merged**
